# 1. Create a 3x3x3 array with random values 

In [1]:
import numpy as np
arr = np.empty((3,3,3))
print(arr)

[[[1.13638893e-316 2.14838399e-316 1.48219694e-323]
  [6.94883404e-310 0.00000000e+000 6.94883404e-310]
  [2.12199579e-314 6.94883404e-310 0.00000000e+000]]

 [[0.00000000e+000 0.00000000e+000 2.12199579e-311]
  [            nan 2.12199579e-314 4.94065646e-324]
  [4.94065646e-324 0.00000000e+000 1.13627826e-316]]

 [[2.02265377e-316 2.12199579e-314 1.46399240e-316]
  [2.47032823e-323 4.94065646e-324 0.00000000e+000]
  [1.13286051e-316 2.00224530e-316 4.94065646e-324]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [2]:
import numpy as np
arr = np.zeros((5,5))
arr[1][0]=1
arr[2][1]=2
arr[3][2]=3
arr[4][3]=4
print(arr)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [3]:
import numpy as np
arr = np.zeros((8,8))
i=0
arr[1::2,::2]=1
arr[::2,1::2]=1
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [4]:
import numpy as np
a = np.random.rand(5,5)
print("Array: ",a)
norm = np.linalg.norm(a)
norm_arr=a/norm
print("Normalized Array:",norm_arr)

Array:  [[0.9718671  0.1404822  0.21089025 0.63565359 0.1152008 ]
 [0.57922694 0.66674198 0.93710477 0.43355891 0.53266167]
 [0.22539272 0.25910519 0.0538514  0.90995057 0.42519626]
 [0.91592385 0.22070282 0.67360131 0.92257461 0.05342806]
 [0.66361536 0.05620773 0.99027901 0.19612246 0.62863846]]
Normalized Array: [[0.32876099 0.047522   0.07133947 0.21502745 0.03896987]
 [0.19593957 0.22554396 0.31700167 0.14666332 0.18018757]
 [0.07624533 0.08764951 0.01821673 0.307816   0.14383442]
 [0.30983663 0.07465885 0.22786431 0.31208644 0.01807352]
 [0.22448629 0.01901382 0.33498933 0.06634386 0.21265439]]


# 5.  How to find common values between two arrays?

In [5]:
arr1 = [1,2,3]
arr2=[2,3,5]
print(np.intersect1d(arr1,arr2))

[2 3]


# 6.How to get the dates of yesterday, today and tomorrow?

In [6]:
import datetime
today=datetime.date.today()
yesterday=today - datetime.timedelta(days=1)
tomorrow = today+datetime.timedelta(days=1)

print(yesterday)
print(today)
print(tomorrow)

2020-07-27
2020-07-28
2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [7]:
a=np.random.rand(2,2)
b=np.random.rand(2,2)
print("a:",a)
print("b:",b)
if (a==b).all():
    print("They are equal")
else:
    print("They are not equal")

a: [[0.92082034 0.01248287]
 [0.74179986 0.00714773]]
b: [[0.45065332 0.61403997]
 [0.37461574 0.50791567]]
They are not equal


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [10]:

v=np.random.rand(10)
print(v)
max_no = np.where(v==v.max())
v[max_no]=0
print(v)

[0.54075274 0.89412683 0.80431627 0.27574789 0.33487386 0.83638751
 0.61265854 0.38197879 0.11538854 0.21816595]
[0.54075274 0.         0.80431627 0.27574789 0.33487386 0.83638751
 0.61265854 0.38197879 0.11538854 0.21816595]


# 9. How to print all the values of an array?

In [11]:

arr = np.array([[1,2,3],[12,23,45]])
print(arr)

[[ 1  2  3]
 [12 23 45]]


# 10.Subtract the mean of each row of a matrix

In [12]:

mat = np.random.rand(2,3)
print(mat)
new_mat = mat -  mat.mean(axis=1,keepdims=True)
print(new_mat)

[[0.22240917 0.83726755 0.80223366]
 [0.73486121 0.33527125 0.19056801]]
[[-0.39822763  0.21663076  0.18159687]
 [ 0.31462772 -0.08496224 -0.22966548]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [13]:
def repeated(v):
    dup_items = set()
    uniq_items = []
    for x in v:
        if x not in dup_items:
            uniq_items.append(x)
            dup_items.add(x)
    return uniq_items
    
import numpy as np
v=np.array([1,2,5,7,8])
index = np.array([1,1,2,0])
new_index=repeated(index)
for a in new_index:
    v[a]=v[a]+1
print(v)

[2 3 6 7 8]


# 12.How to get the diagonal of a dot product?

In [14]:
a=np.array([[1,2,3],[2,5,4]])
b=np.array([[2,3],[8,5],[9,6]])
c=a.dot(b)
print(np.diagonal(c))

[45 55]


# 13.How to find the most frequent value in an array?

In [15]:
import numpy as np
from scipy import stats

a = np.array([1, 3, 4, 2, 2, 2])

bin = np.bincount(a)
print(bin.argmax())

2


# 14.How to get the n largest values of an array

In [16]:

a = np.array([1, 3, 4, 2, 2,2])
n=3
v=a[np.argsort(a)]
print(v[-n:])

[2 3 4]


# 15.How to create a record array from a regular array?

In [17]:
import numpy as np
arra1 = np.array([("VAISHNAVI", 20, 90),
                 ("VARAD", 17, 99),
             ("ANJALI", 48, 91)])
print("Original arrays:")
print(arra1)
print("\nRecord array;")
result = np.core.records.fromarrays(arra1.T,
                              names='NAME, AGE, MARKS')
print(result)

Original arrays:
[['VAISHNAVI' '20' '90']
 ['VARAD' '17' '99']
 ['ANJALI' '48' '91']]

Record array;
[('VAISHNAVI', '20', '90') ('VARAD', '17', '99') ('ANJALI', '48', '91')]
